#pragma once
#include "core.hpp"
namespace meta {
enum class BodyKind:int32_t{Strut=0,Joint=1,Platen=2,Machine=3};
struct Snapshot{Vec3 p;Quat q;Vec3 v,w,half;int material=0,id=0,kind=0,moduleClass=-1,ring=-1,slot=-1;};
struct FrameDiagnostics{double time=0,platenY=0,displacement=0,engineeringStrain=0,engineeringStress=0,reactionForce=0;double loadingWork=0,recoveredWork=0,dissipatedWork=0,specificEnergyAbsorption=0;double elasticEnergy=0,plasticDissipation=0,contactEnergy=0,residualRms=0,residualMax=0,maxPenetration=0;double meanPlasticStrain=0,maxPlasticStrain=0,meanPlasticRotation=0,maxPlasticRotation=0,permanentSet=0;int activeContacts=0,plasticBeams=0,plasticHinges=0,iterations=0;bool converged=false,loading=true;};
struct SimulationResult{std::vector<std::vector<Snapshot>>frames;std::vector<FrameDiagnostics>diagnostics;};
struct MaterialConfig{std::string name="FFF TPU 95A provisional isotropic baseline";double density=1180,young=26e6,nu=.485,yield=5.2e6,hardening=1.4e6,bendHardening=.06,torsionHardening=.045;};
struct SimulationConfig{int cellsX=4,cellsY=6,cellsZ=4;double cellSize=.010,minRadius=.00082,maxRadius=.00122,jointScale=1.18,triggerScale=.38,imperfection=.00022,memberImperfection=.00022;int elementsPerStrut=3;MaterialConfig material;double gravity=9.81,shearCorrection=.62,contactStiffness=1.2e6,contactMargin=2e-5,centeringStiffness=1.5;int contactSamples=3,loadSteps=52,unloadSteps=30,maxIterations=130,history=10,maxLineSearch=22;double maxStrain=.62,stepTime=.06,translationScale=.010,maxTranslationStep=.0022,maxRotationStep=.30;double gradientRmsTolerance=1.2e-3,gradientMaxTolerance=1.5e-2,armijo=1e-4,minLineStep=1e-9,penetrationTolerance=.00012;int maxAdaptiveRefinements=7;int fps=24,frames=83,threads=0;uint64_t seed=0x494e445553545259ULL;};
struct Node{Vec3 x0,x;Quat R;double mass=0;int layer=0;};
struct PlasticState{double epsp=0,alpha=0;Vec3 rotp{0,0,0};double alphaB=0,alphaT=0;};
struct Beam{int a=-1,b=-1,layer=0,family=0;double L0=0,radius=.001,area=0,I=0,J=0;Vec3 e0{1,0,0};PlasticState plastic;};
struct TrialBeam{PlasticState next;double strain=0,stress=0;Vec3 moment{0,0,0};double elastic=0,dissipation=0;bool axialPlastic=false,bendPlastic=false,torsionPlastic=false;};
struct ObjectiveDiag{double elastic=0,plastic=0,contact=0,reaction=0,maxPen=0;int contacts=0;};
struct Objective{double energy=0;std::vector<double>grad;ObjectiveDiag d;std::vector<TrialBeam>trial;};
struct OptStats{int iterations=0,backtracks=0;double rms=INF,max=INF,energy=INF;bool converged=false;};
class Simulator{public:explicit Simulator(SimulationConfig cfg);SimulationResult run();void exportSTL(const std::filesystem::path&path,int radialSegments=12)const;bool rigidRotationTest(double*error=nullptr)const;bool gradientCheck(double*relativeError=nullptr)const;const std::vector<Node>&nodes()const{return nodes_;}const std::vector<Beam>&beams()const{return beams_;}double initialHeight()const{return height_;}double mass()const{return mass_;}double area()const{return area_;}private:SimulationConfig cfg_;std::vector<Node>nodes_;std::vector<Beam>beams_;std::unordered_set<uint64_t>connected_;std::vector<uint8_t>locked_;std::vector<Vec3>baseX_;std::vector<Quat>baseR_;double width_=0,height_=0,depth_=0,area_=0,mass_=0,top0_=0;double loadingWork_=0,recoveredWork_=0,prevDisp_=0,prevForce_=0,reactionOffset_=0;void build();void distributeMass();std::vector<double>zeroVars()const;void state(const std::vector<double>&z,std::vector<Vec3>&x,std::vector<Quat>&R)const;Objective objective(const std::vector<double>&z,double top,bool trials)const;OptStats minimize(double top,std::vector<double>&z,Objective&final);void commit(const std::vector<double>&z,const Objective&o);double topY(double s,bool loading)const;std::vector<Snapshot>capture(double top,const std::vector<Vec3>*prevX,const std::vector<Quat>*prevR)const;FrameDiagnostics diagnostics(double time,double top,bool loading,const Objective&o,const OptStats&s)const;double beamPotential(const std::vector<Vec3>&x,const std::vector<Quat>&R)const;};
}
